- name: Ensure SSH directory exists on all nodes
  ansible.builtin.file:
    path: "/home/{{ rsync_user }}/.ssh"
    state: directory
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0700'

- name: Generate SSH key pair on all nodes (if needed)
  ansible.builtin.openssh_keypair:
    path: "/home/{{ rsync_user }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0600'
    force: true

- name: Install OpenSSH client if not present (for ssh-copy-id)
  ansible.builtin.package:
    name: openssh-client
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Fetch worker's public keys and store on master
  ansible.builtin.fetch:
    src: "/home/{{ rsync_user }}/.ssh/id_rsa.pub"
    dest: "/tmp/{{ item }}_id_rsa.pub"
    flat: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['worker'] }}"

- name: Ensure fetched public key files exist on local machine
  ansible.builtin.stat:
    path: "/tmp/{{ item }}_id_rsa.pub"
  register: key_files
  with_items: "{{ groups['worker'] }}"
  delegate_to: localhost

- name: Copy fetched public keys from local machine to master1 node
  ansible.builtin.copy:
    src: "/tmp/{{ item }}_id_rsa.pub"
    dest: "/tmp/{{ item }}_id_rsa.pub"
  delegate_to: "{{ groups['master1'][0] }}"
  with_items: "{{ groups['worker'] }}"
  become: true

- name: List all copied public key files on master1
  ansible.builtin.find:
    paths: "/tmp"
    patterns: "*_id_rsa.pub"
  register: found_files
  delegate_to: "{{ groups['master1'][0] }}"

- name: Set fact for public key files on master1
  ansible.builtin.set_fact:
    public_key_files: "{{ found_files.files | map(attribute='path') | list }}"
  delegate_to: "{{ groups['master1'][0] }}"

- name: Debug public key files on master1
  ansible.builtin.debug:
    var: public_key_files
  delegate_to: "{{ groups['master1'][0] }}"
- name: Add fetched public keys to master node's authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ rsync_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  become: true
  with_items: "{{ public_key_files }}"

- name: Delete fetched public key files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  become: true
  with_items: "{{ public_key_files }}"

# Ensure known_hosts file exists
- name: Ensure known_hosts file exists
  ansible.builtin.file:
    path: "/home/{{ rsync_user }}/.ssh/known_hosts"
    state: touch
    owner: "{{ rsync_user }}"
    group: "{{ rsync_user }}"
    mode: '0644'
  become: true
- name: Ensure master's SSH key is in workers' known_hosts
  ansible.builtin.known_hosts:
    path: "/home/{{ rsync_user }}/.ssh/known_hosts"
    name: "{{ hostvars[groups['master1'][0]].ansible_host }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H -t rsa ' ~ hostvars[groups['master1'][0]].ansible_host) }}"
    state: present
  become: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"
- name: Ensure workers' SSH keys are in master's known_hosts
  ansible.builtin.known_hosts:
    path: "/home/{{ rsync_user }}/.ssh/known_hosts"
    name: "{{ hostvars[item].ansible_host }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -H -t rsa ' ~ hostvars[item].ansible_host) }}"
    state: present
  become: true
  delegate_to: "{{ groups['master1'][0] }}"
  loop: "{{ groups['worker'] }}"
